spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

spring.liquibase.enabled: true
#spring.liquibase.drop-first: true
spring.liquibase.change-log: classpath:liquibase/master-changelog.xml


#spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
#spring.cloud.stream.kafka.streams.binder.configuration:

spring.cloud.stream.kafka.binder.configuration.auto.offset.reset: earliest

#  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.offset-changed:
  destination: offset-changed
  content-type: application/json
#spring.cloud.stream.kafka.streams.binder:
#  brokers: localhost
spring.application.name: tasks-executions
management.endpoints.web.exposure.include: bindings
cloud.aws.region.static: eu-central-1
server.port: 8082
logging:
  file: application.log


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
   resource:
      userInfoUri: http://localhost:8084/user

feign:
  client:
    config:
      default:
        requestInterceptors:
          com.house.tasktracker.utils.UserContextInterceptor


spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5437/postgres
  username: postgres
  password: test

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#  generate-ddl: true
  show-sql: true

  hibernate:
    ddl-auto: validate

---

spring:
    profiles: aws
spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://tasks-executions.ccells1jzdsb.eu-central-1.rds.amazonaws.com:5432/tasks_executions
  username: postgres
  password: test1234

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#  generate-ddl: true
  show-sql: true

  hibernate:
    ddl-auto: validate

cloud.aws.stack.auto: false
cloud.aws.credentials.instanceProfile: false