spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

spring.liquibase.enabled: true
spring.liquibase.drop-first: true
spring.liquibase.change-log: classpath:liquibase/master-changelog.xml


#spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
#spring.cloud.stream.kafka.streams.binder.configuration:
#  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.offset-changed:
  destination: offset-changed
  content-type: application/json
#spring.cloud.stream.kafka.streams.binder:
#  brokers: localhost
spring.application.name: tasks-executions
management.endpoints.web.exposure.include: bindings
cloud.aws.region.static: eu-central-1
server.port: 8082
logging:
  file: application.log


spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5434/postgres
  username: postgres

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#  generate-ddl: true
  show-sql: true

  hibernate:
    ddl-auto: validate

notifications-service:
 notifications: http://localhost:8083/notifications

---

spring:
    profiles: aws
spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://tasks-executions.ccells1jzdsb.eu-central-1.rds.amazonaws.com:5432/tasks_executions
  username: postgres
  password: test1234

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#  generate-ddl: true
  show-sql: true

  hibernate:
    ddl-auto: validate

cloud.aws.stack.auto: false
cloud.aws.credentials.instanceProfile: false