version: '3'
services:
    kafka:
      image: wurstmeister/kafka
      container_name: kafka-mc
      ports:
        - "9092:9092"
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      depends_on:
        - zookeeper
    zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=zookeeper
    db1:
      image: "postgres:11"
      container_name: "tasks_rules_postgres"
      ports:
        - "5436:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: test
    db2:
      image: "postgres:11"
      container_name: "tasks_executions_postgres"
      ports:
        - "5437:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: test
    db3:
      image: "postgres:11"
      container_name: "notifications_postgres"
      ports:
        - "5435:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: test