spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

spring.liquibase.enabled: true
#spring.liquibase.drop-first: true
spring.liquibase.change-log: classpath:liquibase/master-changelog.xml


#spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
#spring.cloud.stream.kafka.streams.binder.configuration:
#  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.offset-changed:
  destination: offset-changed
  content-type: application/json
  producer:
    partitionKeyExpression: "1"
#spring.cloud.stream.kafka.streams.binder:
#  brokers: localhost
spring.application.name: tasks-rules
management.endpoints.web.exposure.include: bindings
cloud.aws.region.static: eu-central-1
server.port: 8081


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8084/oauth/check_token

logging:
  file: application.log
  level:
    com.house.taskstracker: DEBUG
    com.netflix.hystrix: DEBUG
  pattern.level: '%X{url}%X{extraMdcData} %5p'

logging.level.org.springframework.security.web.FilterChainProxy: DEBUG

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5436/postgres
  username: postgres
  password: test

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#  generate-ddl: true
  show-sql: true

  hibernate:
    ddl-auto: validate

---

spring:
    profiles: aws
spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://tasks-rules.ccells1jzdsb.eu-central-1.rds.amazonaws.com:5432/tasks_rules
  username: postgres
  password: test1234

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#  generate-ddl: true
  show-sql: true

  hibernate:
    ddl-auto: validate

cloud.aws.stack.auto: false
cloud.aws.credentials.instanceProfile: false