spring.application.name: authentication
management.endpoints.web.exposure.include: bindings
cloud.aws.region.static: eu-central-1
server.port: 8084
logging:
  file: application.log


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/


spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5434/postgres
  username: postgres

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#  generate-ddl: true
  show-sql: true

  hibernate:
    ddl-auto: validate


spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

spring.liquibase.enabled: true
spring.liquibase.drop-first: true
spring.liquibase.change-log: classpath:liquibase/master-changelog.xml
