spring.application.name: zuulsvr-service

zuul.prefix: /api

server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/


zuul.sensitiveHeaders: Cookie,Set-Cookie