spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

spring.liquibase.enabled: true
#spring.liquibase.drop-first: true
spring.liquibase.change-log: classpath:liquibase/master-changelog.xml


spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5435/postgres
  username: postgres
  password: test

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#  generate-ddl: true
  show-sql: true

  hibernate:
    ddl-auto: validate



spring.application.name: notifications-service
server.port: 8083
logging:
  file: application.log


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
   resource:
      userInfoUri: http://localhost:8084/user

feign:
  client:
    config:
      default:
        requestInterceptors:
          com.house.tasktracker.utils.UserContextInterceptor